
//************************** USING ITERATIVE METHOD ***********************

// #include<iostream>
// using namespace std;
// int main ()
// {
//     int a,i;
//     int fact = 1;
//     cout<<"Enter the number thats you want to find the factorial "<<endl;
//     cin>>a;
//     for(i=1;i<=a;i++)
//     {
//         fact = fact * i;
//     }
//     printf("The factorial of %d is %d ",a,fact);
//     return 0;
// }

//************************ USING RECURSION METHOD *************************

// #include<iostream>
// using namespace std;
// int fact (int x)
// {
//     if(x<2)
//     {
//         return 1;
//     }
//     return x*fact(x-1);
// }
// int main ()
// {
//     int a;
//     cout<<"Enter the number that's you want to find their factorial "<<endl;
//     cin>>a;
//     cout<<"The factorail of "<<a<<" is "<<fact(a)<<endl;
//     return 0;
// }
